name: Docker Build for PHP 7.3

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile-7.3'
      - 'docker-*'

env:
  VERSION: '7.3'

jobs:
  build:
    name: Build Testing
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and cache
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-${{ env.VERSION }}
          target: builder
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          cache-to: type=gha, mode=max
          outputs: type=cacheonly
