name: Docker Build for PHP 8.0

on:
  push:
    branches:
      - '**'
    paths:
      - 'Dockerfile-8.0'
      - 'docker-*'

env:
  USERNAME: akafeng
  REPOSITORY: php
  GITHUB_PACKAGE_REGISTRY: docker.pkg.github.com
  VERSION: '8.0'

jobs:
  build:
    name: Build Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.GITHUB_PACKAGE_REGISTRY }} -u ${{ env.USERNAME }} --password-stdin

      - name: Docker Build
        env:
          DOCKERFILE: Dockerfile-${{ env.VERSION }}
          STAGE_CACHE: ${{ env.GITHUB_PACKAGE_REGISTRY }}/${{ github.repository }}/${{ env.REPOSITORY }}:${{ env.VERSION }}-stage
        run: |
          docker build \
            --target builder \
            --tag=${{ env.STAGE_CACHE }} \
            --file=${{ env.DOCKERFILE }} \
            .
          docker build \
            --cache-from=${{ env.STAGE_CACHE }} \
            --file=${{ env.DOCKERFILE }} \
            .

      - name: Docker Publish
        run: docker push --all-tags ${{ env.GITHUB_PACKAGE_REGISTRY }}/${{ github.repository }}/${{ env.REPOSITORY }}
