name: Docker Build

on:
  push:
    tags-ignore:
      - '**'
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build
        run: docker build --cache-from=akafeng/php .
