name: Docker Publish

on:
  release:
    types:
      - published

env:
  REPOSITORY: php
  PACKAGE_REGISTRY: ghcr.io

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Process version
        id: version
        uses: ncipollo/semantic-version-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.PACKAGE_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.PACKAGE_REGISTRY }}/${{ github.repository_owner }}/${{ env.REPOSITORY }}
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile-${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          cache-from: type=gha, scope=php-${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
